### ISSUE TITLE
Using client library outside Terraform

### ISSUE THREAD

**Issue by JordanSussman** [sysdiglabs/terraform-provider-sysdig#32]
I have interest in utilizing/contributing the [secure library](https://github.com/draios/terraform-provider-sysdig/tree/master/sysdig/secure) beyond the context of Terraform. Couple of questions around that:

- Are you open to contributions that do not include terraform resources?
- Any intention to extract the library into a separate repository like https://github.com/draios/python-sdc-client?

**Comment by nestorsalceda** [comment]
Hey Jordan,

This is a pretty good question, and comes in a great timing. A couple of days ago I was talking with my team about this because we are writing several golang integrations and each one of us are doing a different Secure Client implementation.

Yes, we do have intention to extract the library to a separate repository and of course we will be open to contributions. The bad news is that I don't have an ETA for this.

IMHO this is pretty important because the following reasons:

* It would allow us to discover new use cases about how people is using Sysdig Platform
* Golang has a lot of popularity between SRE / DevOps / Operations teams and this will enable them to scratch their own itches

I'm going to try to prioritize this and I will come back.

Thanks for opening this conversation

**Comment by tembleking** [comment]
@JordanSussman I am closing this issue here because we will be working on the [Sysdig SDK for Go](https://github.com/sysdiglabs/sysdig-sdk-go) which is going to be a client in Golang. We will be adding features to the other repo soon, stay tuned! :smiley:

**Comment by JordanSussman** [comment]
@tembleking - any news you can share on the progress of this? I'd be happy to help test out the package once available.
