### ISSUE TITLE
about Monitor Authentication

### ISSUE THREAD

**Issue by go-test-sysdig** [sysdiglabs/terraform-provider-sysdig#551]
I am going to add a Role using tf, although my mistake caused me to write the wrong option in the authentication, the Role addition still succeeded, is this the correct situation?
Here's the tf file I used, and you can see that I wrote “sysdig_monitor_api_token” instead of “sysdig_secure_api_token”.
```terraform
terraform {
  required_providers {
    sysdig = {
      source = "sysdiglabs/sysdig"
      version = ">=0.5"
    }
  }
}

provider "sysdig" {
  sysdig_secure_url="https://secure.sysdig.com"
  sysdig_monitor_api_token  = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}
```
I just tried adding Role and Team.
Adding a Role worked but adding a Team failed.

**Comment by dbonf** [comment]
hi, not sure if I understood what resources you tried to create, I assume a `sysdig_custom_role` and a `sysdig_secure_team`?

In that case, the fact that the custom role was created and the team was not is expected, since `sysdig_custom_role` is a resource that can be created by defining either secure product credentials or monitor product credentials (it is listed under "Sysdig Platform" in the [doc](https://registry.terraform.io/providers/sysdiglabs/sysdig/latest/docs)), while the `sysdig_secure_team` is a resource that can be created only with secure product credentials (it is listed under "Sysdig Secure"), and if you need a monitor team, you create the `sysdig_monitor_team` companion resource.
